apiVersion: apps/v1
kind: Deployment
metadata:
  name: openreview-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openreview-tier
  template:
    metadata:
      labels:
        app: openreview-tier
    spec:
      containers:
      - name: frontend-container
        image: devopslabfinal-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
      - name: backend-container
        image: devopslabfinal-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-cluster-service:27017/openreview"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openreview-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openreview-db
  template:
    metadata:
      labels:
        app: openreview-db
    spec:
      containers:
      - name: db-container
        image: mongo:6.0
        ports:
        - containerPort: 27017