apiVersion: v1
kind: Service
metadata:
  name: openreview-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: api
    port: 5000
    targetPort: 5000
  selector:
    app: openreview