name: DevOps Lab Final Pipeline

on:
  push:
    branches: [ "Main", "main", "master" ]
  pull_request:
    branches: [ "Main", "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and Build Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Install and Build Frontend Dependencies
        run: |
          cd frontend
          npm install --prefer-offline --no-audit

  build-and-push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # This runs a local test-build stage to verify your multi-service Docker files match exam specs
      - name: Verify Docker Compose Build Assembly
        run: |
          docker compose build